In [ ]:
# numerical computation,   for pyhton it is called as numpy,
# this is derived from matlab
# Data Manipulation

In [1]:
import numpy as np

In [2]:
l = [1,2,3,4,6]   # hetrogeniou collection of data

In [3]:
np.array(l)  

array([1, 2, 3, 4, 6])

In [5]:
l1 = [4,5,6,'sharan', 34.45, True]

In [10]:
 a1 = np.array(l1)   # it has converted onto string(Higher order), since l1 has diff data types

In [11]:
a2 = np.array([[1,2,3], [4,5,6]])

In [12]:
a3 = np.array([[[1,2,3], [4,5,6], [7,8,9]]])

In [13]:
a1

array(['4', '5', '6', 'sharan', '34.45', 'True'], dtype='<U32')

In [14]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
a3

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [5]:
a5 = np.random.randint(1,90, (6,5))

In [6]:
a5

array([[82, 14, 41, 46, 49],
       [43, 16, 55, 71, 12],
       [ 9, 36, 25, 64, 51],
       [ 3, 76, 83, 66, 15],
       [ 1, 84,  7, 27, 32],
       [47, 10, 23, 38, 27]])

In [7]:
a5[a5>40]

array([82, 41, 46, 49, 43, 55, 71, 64, 51, 76, 83, 66, 84, 47])

In [16]:
a1.ndim

1

In [17]:
a2.ndim

2

In [19]:
a3.ndim

3

In [20]:
a1.size

6

In [21]:
a2.size

6

In [22]:
a3.size       # it will give no of elements

9

In [23]:
a1.shape

(6,)

In [24]:
a2.shape           # rows x column it will give

(2, 3)

In [25]:
a3.shape      # z, x, y

(1, 3, 3)

In [26]:
a1

array(['4', '5', '6', 'sharan', '34.45', 'True'], dtype='<U32')

In [27]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [28]:
a3

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [37]:
np.random.randint(2,50 , (3,4))  # generate random data 3 rows and 4 column

array([[46, 22, 22, 41],
       [25,  7, 29, 18],
       [22, 10, 47, 26]])

In [38]:
np.random.randint(2,50 , (2,3,4))       3 x 4 and 2 metrix\layes

array([[[20, 31,  9, 17],
        [28, 24, 37, 18],
        [ 2, 41, 13, 11]],

       [[37, 43, 20, 42],
        [ 8, 21, 31, 19],
        [48, 30, 34, 18]]])

In [39]:
np.random.rand(2,3)   # any mean and std davition

array([[0.04769155, 0.04337276, 0.49494016],
       [0.64747708, 0.31722617, 0.30940591]])

In [40]:
# to noramalise data we need random data

In [41]:
np.random.randn(4,4)       # normal distubution , avg/mean =0,  standard daviation is one

array([[ 0.38048844, -0.59889568, -0.16047464, -0.68102806],
       [-1.07529343, -0.91508607,  1.86056968,  0.08509605],
       [-1.94049467,  0.25106879, -0.36755731,  0.97199107],
       [ 0.30711999, -2.71767321, -0.63637881, -0.28281725]])

In [42]:
# if i want to change the shape of data

a4 = np.random.randn(4,4)       

In [45]:
a4.reshape(2,8)

array([[ 0.14719076,  1.02167438,  1.28209244,  0.41648522, -0.10706166,
        -0.9535261 , -0.58597381, -0.70552486],
       [ 1.33093441,  0.41913544, -1.20274431, -1.18445164, -0.23256148,
         0.82466644, -0.17923489, -0.60659442]])

In [47]:
a4.reshape(16,1)

array([[ 0.14719076],
       [ 1.02167438],
       [ 1.28209244],
       [ 0.41648522],
       [-0.10706166],
       [-0.9535261 ],
       [-0.58597381],
       [-0.70552486],
       [ 1.33093441],
       [ 0.41913544],
       [-1.20274431],
       [-1.18445164],
       [-0.23256148],
       [ 0.82466644],
       [-0.17923489],
       [-0.60659442]])

In [46]:
a4.reshape(2,-1)

array([[ 0.14719076,  1.02167438,  1.28209244,  0.41648522, -0.10706166,
        -0.9535261 , -0.58597381, -0.70552486],
       [ 1.33093441,  0.41913544, -1.20274431, -1.18445164, -0.23256148,
         0.82466644, -0.17923489, -0.60659442]])

In [48]:
a4.reshape(2,-3)

array([[ 0.14719076,  1.02167438,  1.28209244,  0.41648522, -0.10706166,
        -0.9535261 , -0.58597381, -0.70552486],
       [ 1.33093441,  0.41913544, -1.20274431, -1.18445164, -0.23256148,
         0.82466644, -0.17923489, -0.60659442]])

In [50]:
a4.reshape(2,2,4)              

array([[[ 0.14719076,  1.02167438,  1.28209244,  0.41648522],
        [-0.10706166, -0.9535261 , -0.58597381, -0.70552486]],

       [[ 1.33093441,  0.41913544, -1.20274431, -1.18445164],
        [-0.23256148,  0.82466644, -0.17923489, -0.60659442]]])

In [51]:
a1

array(['4', '5', '6', 'sharan', '34.45', 'True'], dtype='<U32')

In [52]:
a1[0]

'4'

In [54]:
a1[2:6]   # able to do a  slicing operation

array(['6', 'sharan', '34.45', 'True'], dtype='<U32')

In [55]:
a1[2:6:2]

array(['6', '34.45'], dtype='<U32')

In [56]:
a1[::-1]

array(['True', '34.45', 'sharan', '6', '5', '4'], dtype='<U32')

In [57]:
a3

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [58]:
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [59]:
a2[0]

array([1, 2, 3])

In [63]:
a2[:,1:]

array([[2, 3],
       [5, 6]])

In [65]:
a2[:,[1,2]]

array([[2, 3],
       [5, 6]])

## 

In [66]:
a2[[0,1], 1:]

array([[2, 3],
       [5, 6]])

In [68]:
a5 = np.random.randint(2,90 , (6,5))

In [69]:
a5

array([[69, 62, 81, 47, 86],
       [62, 46, 54, 86, 16],
       [32, 41,  6,  3, 34],
       [86, 11, 75, 70, 79],
       [80,  8, 59, 25, 56],
       [79, 25, 79, 69, 83]])

In [70]:
a5[a5>40]

array([69, 62, 81, 47, 86, 62, 46, 54, 86, 41, 86, 75, 70, 79, 80, 59, 56,
       79, 79, 69, 83])

In [71]:
a5

array([[69, 62, 81, 47, 86],
       [62, 46, 54, 86, 16],
       [32, 41,  6,  3, 34],
       [86, 11, 75, 70, 79],
       [80,  8, 59, 25, 56],
       [79, 25, 79, 69, 83]])

In [72]:
# reassignment opearion 

In [73]:
a5[0,1]

62

In [74]:
a5[0,1] = 100

In [75]:
a5

array([[ 69, 100,  81,  47,  86],
       [ 62,  46,  54,  86,  16],
       [ 32,  41,   6,   3,  34],
       [ 86,  11,  75,  70,  79],
       [ 80,   8,  59,  25,  56],
       [ 79,  25,  79,  69,  83]])

In [9]:
a6 = np.random.randint(0,3,  (3,3))

In [10]:
a7 = np.random.randint(0,3,  (3,3))

In [11]:
a6

array([[1, 0, 2],
       [0, 2, 1],
       [0, 2, 1]])

In [12]:
a7

array([[1, 2, 1],
       [2, 1, 0],
       [1, 1, 0]])

In [13]:
a6*a7    # this do element wise multiplication not metrix multiplication

array([[1, 0, 2],
       [0, 2, 0],
       [0, 2, 0]])

In [14]:
# to do metrix multiplication, no of col of 1st metrix same as rows of 2nd metrix

In [15]:
a6@a7    # this will give metrix multiplication

array([[3, 4, 1],
       [5, 3, 0],
       [5, 3, 0]])

In [16]:
a6

array([[1, 0, 2],
       [0, 2, 1],
       [0, 2, 1]])

In [17]:
a6+100   # element wise operation

array([[101, 100, 102],
       [100, 102, 101],
       [100, 102, 101]])

In [18]:
a6*2

array([[2, 0, 4],
       [0, 4, 2],
       [0, 4, 2]])

In [19]:
a6/0

C:\Users\User\AppData\Local\Temp/ipykernel_9132/1058679823.py:1: RuntimeWarning: divide by zero encountered in true_divide
  a6/0
C:\Users\User\AppData\Local\Temp/ipykernel_9132/1058679823.py:1: RuntimeWarning: invalid value encountered in true_divide
  a6/0


array([[inf, nan, inf],
       [nan, inf, inf],
       [nan, inf, inf]])

In [20]:
a6

array([[1, 0, 2],
       [0, 2, 1],
       [0, 2, 1]])

In [21]:
a6**3   # it will perform power operation

array([[1, 0, 8],
       [0, 8, 1],
       [0, 8, 1]], dtype=int32)

In [31]:
a8 = np.zeros((4,4))  # @ all element value will be one
a8
#np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [32]:
a9 = np.ones((4,5))   # all element value will be one
a9

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [26]:
a9+10

array([[11., 11., 11., 11., 11.],
       [11., 11., 11., 11., 11.],
       [11., 11., 11., 11., 11.],
       [11., 11., 11., 11., 11.]])

In [27]:
a9 + np.array([1,2,3,4,5])   # row wise addition/ broadcating operation

array([[2., 3., 4., 5., 6.],
       [2., 3., 4., 5., 6.],
       [2., 3., 4., 5., 6.],
       [2., 3., 4., 5., 6.]])

In [108]:
a9 + np.array([1,2,3,4])   # shape should be same ie no of element in row must be same in 

ValueError: operands could not be broadcast together with shapes (4,5) (4,) 

In [109]:
a9

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [28]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [29]:
np.array([1,2,3,4]).T

array([1, 2, 3, 4])

In [30]:
np.array([[1,2,3,4]]).T + a9 # able to rotate/transpose operation in column wise

array([[2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5.]])

In [112]:
np.array([[1,2,3,4]]).T

array([[1],
       [2],
       [3],
       [4]])

In [113]:
a6

array([[2, 1, 1],
       [0, 2, 0],
       [2, 1, 0]])

In [115]:
a6.T     # it rotated matrix or transposed a matrix

array([[2, 0, 2],
       [1, 2, 1],
       [1, 0, 0]])

In [116]:
a5

array([[ 69, 100,  81,  47,  86],
       [ 62,  46,  54,  86,  16],
       [ 32,  41,   6,   3,  34],
       [ 86,  11,  75,  70,  79],
       [ 80,   8,  59,  25,  56],
       [ 79,  25,  79,  69,  83]])

In [117]:
np.sqrt(a5)  # this will give sqr root of a5 matrix

array([[ 8.30662386, 10.        ,  9.        ,  6.8556546 ,  9.2736185 ],
       [ 7.87400787,  6.78232998,  7.34846923,  9.2736185 ,  4.        ],
       [ 5.65685425,  6.40312424,  2.44948974,  1.73205081,  5.83095189],
       [ 9.2736185 ,  3.31662479,  8.66025404,  8.36660027,  8.88819442],
       [ 8.94427191,  2.82842712,  7.68114575,  5.        ,  7.48331477],
       [ 8.88819442,  5.        ,  8.88819442,  8.30662386,  9.11043358]])

In [118]:
np.exp(a5)         #exponantial

array([[9.25378173e+29, 2.68811714e+43, 1.50609731e+35, 2.58131289e+20,
        2.23524660e+37],
       [8.43835667e+26, 9.49611942e+19, 2.83075330e+23, 2.23524660e+37,
        8.88611052e+06],
       [7.89629602e+13, 6.39843494e+17, 4.03428793e+02, 2.00855369e+01,
        5.83461743e+14],
       [2.23524660e+37, 5.98741417e+04, 3.73324200e+32, 2.51543867e+30,
        2.03828107e+34],
       [5.54062238e+34, 2.98095799e+03, 4.20121040e+25, 7.20048993e+10,
        2.09165950e+24],
       [2.03828107e+34, 7.20048993e+10, 2.03828107e+34, 9.25378173e+29,
        1.11286375e+36]])

In [119]:
np.log10(a5)                #logarithemic

array([[1.83884909, 2.        , 1.90848502, 1.67209786, 1.93449845],
       [1.79239169, 1.66275783, 1.73239376, 1.93449845, 1.20411998],
       [1.50514998, 1.61278386, 0.77815125, 0.47712125, 1.53147892],
       [1.93449845, 1.04139269, 1.87506126, 1.84509804, 1.89762709],
       [1.90308999, 0.90308999, 1.77085201, 1.39794001, 1.74818803],
       [1.89762709, 1.39794001, 1.89762709, 1.83884909, 1.91907809]])

In [120]:
# all matamatical operation available inside this numpy library

In [121]:
range(0,10)

range(0, 10)

In [125]:
list(range(0,10, 2))

[0, 2, 4, 6, 8]

In [124]:
list(range(0,10, 2.5))

TypeError: 'float' object cannot be interpreted as an integer

In [33]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
np.arange(1,10, 2)

array([1, 3, 5, 7, 9])

In [35]:
np.arange(1,10, 2.5)  # it except floating point in arange function

array([1. , 3.5, 6. , 8.5])

In [36]:
np.linspace(2,3,num=50)             # it generate a 50 numbers within 2-3 range

# this consider linear scale

array([2.        , 2.02040816, 2.04081633, 2.06122449, 2.08163265,
       2.10204082, 2.12244898, 2.14285714, 2.16326531, 2.18367347,
       2.20408163, 2.2244898 , 2.24489796, 2.26530612, 2.28571429,
       2.30612245, 2.32653061, 2.34693878, 2.36734694, 2.3877551 ,
       2.40816327, 2.42857143, 2.44897959, 2.46938776, 2.48979592,
       2.51020408, 2.53061224, 2.55102041, 2.57142857, 2.59183673,
       2.6122449 , 2.63265306, 2.65306122, 2.67346939, 2.69387755,
       2.71428571, 2.73469388, 2.75510204, 2.7755102 , 2.79591837,
       2.81632653, 2.83673469, 2.85714286, 2.87755102, 2.89795918,
       2.91836735, 2.93877551, 2.95918367, 2.97959184, 3.        ])

In [131]:
np.logspace(2,3,num=4, base=10)    # it generate a 4 numbers within 2-3 range with base 10,

# this consider logarithemic scale

array([ 100.        ,  215.443469  ,  464.15888336, 1000.        ])

In [132]:
np.eye(5)       # identity metrix, diagnal is 1 and determanant = 1

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [137]:
# Data Visualisation